### ISSUE TITLE
App stuck on "Select brand"

### ISSUE THREAD

**Issue by Axonym** [regulad/SupIR#1]
When I try to open up the app it doesn't load up the layout to select the brand.
I took a look at the logcat and it loads every database csv file but it still is loading.

**Comment by regulad** [comment]
I was able to reproduce this on my Samsung Galaxy S4 with LineageOS 13, but as you said I saw typical behavior in the logcat stream and could not determine the source of the error. PRs welcome!

**Comment by rafnov** [comment]
Same on me Galaxy S5 Lineage OS 18.1 @ Android 11.
Select brand + circle in the middle. Nothing else.

**Comment by sanctimoniousape** [comment]
Ditto. [Unihertz Jelly Star](https://www.unihertz.com/products/jelly-star) on Android 13.  Was afraid it was the tiny screen throwing things for a loop, glad to see it's not.

**Comment by biazzotto** [comment]
Same here... Poco X6 Pro, Xiaomi HyperOS 1.0.12 @ Android 14...

**Comment by MrNessuno** [comment]
Same issue 
Poco f2 pro 
Android 14 crDroid

**Comment by lcdss** [comment]
Same for me on Poco F3 with custom rom (crDroid 10.9 - Android 14). You open the app and it get stuck loading something.

**Comment by regulad** [comment]
Fixed in v1.1.0, releasing soon

**Comment by rafnov** [comment]
Working now, but unfortunately doesn't have my tv in database.

**Comment by regulad** [comment]
Sorry about that. The app hides codes that the phone isn’t capable of
transmitting, so maybe try another phone?
